// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8XGtulq13gmZGm0IAGcvUXfOQ9vTM6do',
    appId: '1:857837821643:web:87d3e78426d32ab5a1c54e',
    messagingSenderId: '857837821643',
    projectId: 'ada-ecommerce-649fe',
    authDomain: 'ada-ecommerce-649fe.firebaseapp.com',
    storageBucket: 'ada-ecommerce-649fe.firebasestorage.app',
    measurementId: 'G-65557F3D3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlryr0n8nRZqTFRBb90-ZLVx-0LbBnr5Y',
    appId: '1:857837821643:android:a0b8543d86ea7ea5a1c54e',
    messagingSenderId: '857837821643',
    projectId: 'ada-ecommerce-649fe',
    storageBucket: 'ada-ecommerce-649fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDTFSB7WZU8QI-xvX_Q0lDYbG9aBFTWB4',
    appId: '1:857837821643:ios:0e5eec18d7669f95a1c54e',
    messagingSenderId: '857837821643',
    projectId: 'ada-ecommerce-649fe',
    storageBucket: 'ada-ecommerce-649fe.firebasestorage.app',
    iosBundleId: 'com.example.ada',
  );
}
