name: "Build & Release APK"

on:
  push:
    branches:
      - news-app-with-auth
      - note_app_api
      - note_app

jobs:
  build:
    name: Build & Upload APK
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload to Firebase App Distribution
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app "1:857837821643:android:a0b8543d86ea7ea5a1c54e" \
            --testers "abdallhesam100@gmail.com,abdallhesam5@gmail.com" \
            --release-notes "نسخة تجريبية جديدة"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
